services:
  api:
    build: .
    container_name: devia-api
    env_file:
      - .env
    ports:
      - "8787:8787"
    volumes:
      - ./app:/app/app
      - ./config:/app/config
      - ./data:/app/data
    networks:
      - default
      - intranet_shared
    restart: unless-stopped

networks:
  intranet_shared:
    external: true
    name: timone_timone
